[workspace]
resolver = "3"
members = [
    "btree",
    "htable",
    "list",
    "vec"
]

[workspace.package]
name = "collections"
version = "0.1.0"
authors = ["Patman1O1"]
edition = "2024"
description = ""
readme = "README.md"
repository = "https://github.com/Patman1O1/rust-collections"
license = "MIT"
license-file = "LICENSE"
build = "build.rs"


[workspace.dependencies]
allocator-api2 = "0.4.0"
